version: "3.7"

services:
  letsplay_api:
    image: letsplay_api
    container_name: 'letsplay_api'
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - .:/app/
      - /app/node_modules
      - ./logs:/app/logs
    networks: 
      - backend
    depends_on: 
      - letsplay-db
    ports:
      - "3030:3030"
    env_file: 
      - .env
    environment:
      PORT: 3030
      BASE_URL: localhost
      DB_DIALECT: postgres
      DB_PORT: 5432
      DB_HOST: letsplay-db
      DB_NAME: LetsPlay
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_TIME: 20
      GMAIL_EMAIL: ${GMAIL_EMAIL}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      EMAIL_PORT: 587
      EMAIL_SMTP_HOST: smtp.gmail.com
      FIREBASE_CREDENTIALS: /app/letsplay-firebase.json
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
    command: npm run start

  letsplay-db:
    image: postgres
    container_name: 'letsplay-db'
    restart: unless-stopped
    volumes:
      - ./config/database/init.sql:/data/application/init.sql
      - local_db_data:/var/lib/postgresql/data
    env_file: 
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: LetsPlay
    ports:
      - "5432:5432"
    networks: 
      - backend

  pg-admin:
    image: dpage/pgadmin4
    container_name: 'pgadmin4_letsplay'
    restart: unless-stopped
    depends_on: 
      - letsplay-db
    volumes: 
      - pgadmin-data:/var/lib/pgadmin
    networks: 
      - backend
    ports:
      - "5051:80"
    env_file: 
      - .env
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    
volumes:
  local_db_data:
  pgadmin-data:
  node_modules:
  logs:
  
networks:
  backend:
    driver: 'bridge'